version: '3.8'

services:
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend-java:
    build:
      context: ./backend-java
      dockerfile: Dockerfile
    container_name: backend-java
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

  ml-scoring-python:
    build:
      context: ./ml-scoring-python
      dockerfile: Dockerfile
    container_name: ml-scoring-python
    depends_on:
      - redis
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
