server:
  port: 8080

kafka:
  bootstrap-servers: localhost:9092
  topic: transactions

redis:
  host: localhost
  port: 6379
  cache-ttl-seconds: 300

ml:
  scoring-endpoint: http://localhost:5000/score

logging:
  level: INFO

